{
    'name': 'Sale',
    'version': '13.0.0.1',
    'summary': """ Sale """,
    'description': """ Sale """,
    'author': 'GeoTechnosoft',
    'license': 'AGPL-3',
    'website': 'http://www.geotechnosoft.com',
    'category': '',
    'depends': ['base', 'sale', 'l10n_in_sale', 'sale_management', 'sales_team', 'sale_crm', 'mail', 'purchase',
                'sale_margin', 'sale_enterprise'],
    'data': [
        'security/ir.model.access.csv',
        'security/security_view.xml',
        # 'data/mail_data.xml',
        'wizard/request_modify_view.xml',
        'wizard/cancel_wizard_view.xml',
        'views/sale_view.xml',
        'views/pending_approval.xml',
        'views/email_compose_view.xml',
        'template/email_templates.xml',
        'template/invoice_create_approval_view.xml',
        'report/report_sale_without_header.xml',
        'report/report_view.xml',
    ],

    'installable': True,
    'application': True,
}
